### ISSUE TITLE
Pharmacy replaces apothecary but is worse.

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#100]
@raxo2222 

![image](https://user-images.githubusercontent.com/1453936/64389032-f04f8500-d038-11e9-9e1a-898cde907fd3.png)

**Comment by raxo2222** [comment]
https://github.com/caveman2cosmos/Caveman2Cosmos/issues/94#issuecomment-528629022
This is issue with wonder yield/commerce bonus on regular buildings - X gets this, but not replacement of X.
So Apothecary Shop gets+5 gold from guild unlike Pharmacy.

**Comment by raxo2222** [comment]
You can't target "line" of buildings - instead you must pick building and its replacements individually.

**Comment by billw2012** [comment]
Yeah we could add this then, seems like something we want to do often, and it saves a lot of extra tagging in the xml?

**Comment by raxo2222** [comment]
Building class was used only for unique buildings in cin4.
Now only continental cultures actually utilize that.

**Comment by raxo2222** [comment]
I think I fixed this bug now: https://github.com/caveman2cosmos/Caveman2Cosmos/commit/75ad982a5e29cdcc7d51c5fccc095c9836babe89
I added upgrades, that were unlocked before obsoletion of wonders to GlobalBuildingExtraCommerces tag.

**Comment by billw2012** [comment]
@raxo2222 
So pharmacy still shows as bad in the save this was noted in (after recalc):
![image](https://user-images.githubusercontent.com/1453936/64448978-d6647f80-d0d6-11e9-8665-59beeb8d5a67.png)
No +5 for it, only for the apocathery it replaces.

**Comment by Toffer90** [comment]
Yeah, the first line there doesn't take into account how other buildings in the city may affect it.
That is what actual do.

The pharmacy is supposed to be more expensive than the apothecary shop btw.

**Comment by billw2012** [comment]
Okay so probably another thing we can do in the tooltip then, can use whatever logic calculates for the built building for the tooltip to get the modified value, I will add another separate bug for this then and leave this bug closed.
